apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-8-janus
  namespace: janusgraph
spec:
  version: 8.10.4
  http:
    tls:
      selfSignedCertificate:
        disabled: true 

  nodeSets:
  - name: default
    count: 2
    config:
      node.store.allow_mmap: false
      xpack.security.authc:
        anonymous:
          username: anonymous
          roles: superuser
          authz_exception: false
