apiVersion: v1
kind: ConfigMap
metadata:
  name: janusgraph-kubernetes-config
  namespace: janusgraph
data:
  kubernetes-conf.properties: |
    gremlin.graph = org.janusgraph.core.JanusGraphFactory
    storage.backend = cql
    storage.hostname = scylla-janus-client.janusgraph.svc.cluster.local
    storage.cql.keyspace = janusgraph
    cache.db-cache = true
    cache.db-cache-clean-wait = 20
    cache.db-cache-time = 180000
    cache.db-cache-size = 0.25
    index.search.backend = elasticsearch
    index.search.hostname = elastic-7-janus-es-http.janusgraph.svc.cluster.local